/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InterviewSetupRouteImport } from './routes/interview.setup'
import { Route as InterviewSessionRouteImport } from './routes/interview.session'
import { Route as InterviewResultsRouteImport } from './routes/interview.results'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewSetupRoute = InterviewSetupRouteImport.update({
  id: '/interview/setup',
  path: '/interview/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewSessionRoute = InterviewSessionRouteImport.update({
  id: '/interview/session',
  path: '/interview/session',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewResultsRoute = InterviewResultsRouteImport.update({
  id: '/interview/results',
  path: '/interview/results',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/interview/results': typeof InterviewResultsRoute
  '/interview/session': typeof InterviewSessionRoute
  '/interview/setup': typeof InterviewSetupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/interview/results': typeof InterviewResultsRoute
  '/interview/session': typeof InterviewSessionRoute
  '/interview/setup': typeof InterviewSetupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/interview/results': typeof InterviewResultsRoute
  '/interview/session': typeof InterviewSessionRoute
  '/interview/setup': typeof InterviewSetupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/profile'
    | '/signup'
    | '/interview/results'
    | '/interview/session'
    | '/interview/setup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/profile'
    | '/signup'
    | '/interview/results'
    | '/interview/session'
    | '/interview/setup'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/profile'
    | '/signup'
    | '/interview/results'
    | '/interview/session'
    | '/interview/setup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  InterviewResultsRoute: typeof InterviewResultsRoute
  InterviewSessionRoute: typeof InterviewSessionRoute
  InterviewSetupRoute: typeof InterviewSetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/setup': {
      id: '/interview/setup'
      path: '/interview/setup'
      fullPath: '/interview/setup'
      preLoaderRoute: typeof InterviewSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/session': {
      id: '/interview/session'
      path: '/interview/session'
      fullPath: '/interview/session'
      preLoaderRoute: typeof InterviewSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/results': {
      id: '/interview/results'
      path: '/interview/results'
      fullPath: '/interview/results'
      preLoaderRoute: typeof InterviewResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  InterviewResultsRoute: InterviewResultsRoute,
  InterviewSessionRoute: InterviewSessionRoute,
  InterviewSetupRoute: InterviewSetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
